# Generated by Django 3.0.3 on 2020-04-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRPModels',
            fields=[
                ('device_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('challenge', models.CharField(max_length=1024)),
                ('response', models.CharField(max_length=257)),
                ('used_times', models.IntegerField()),
            ],
        ),
    ]
