# Generated by Django 3.0.5 on 2020-04-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRPModels',
            fields=[
                ('device_id', models.CharField(max_length=64)),
                ('challenge', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('response', models.CharField(max_length=257)),
                ('used_times', models.CharField(max_length=100)),
                ('update_time', models.CharField(max_length=100)),
                ('identity', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CRPTModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64)),
                ('challenge', models.CharField(max_length=1024)),
                ('response', models.CharField(max_length=257)),
                ('used_times', models.CharField(max_length=100)),
                ('update_time', models.CharField(max_length=100)),
            ],
        ),
    ]
